ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_smmu_api.o
