ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
