ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_lrme
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_lrme/lrme_hw_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -Idrivers/media/platform/msm/camera-renovation
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include/

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += lrme_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_lrme_dev.o cam_lrme_context.o
