ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_eeprom_dev.o cam_eeprom_core.o cam_eeprom_soc.o
