ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_isp/isp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cdm/

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += isp_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_isp_dev.o cam_isp_context.o
