ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/cpas_top
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/camss_top

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cpas_top/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += camss_top/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_cpas_soc.o cam_cpas_intf.o cam_cpas_hw.o