ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera-renovation
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += icp_hw/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_icp_subdev.o cam_icp_context.o hfi.o
