ccflags-y += -Idrivers/media/platform/msm/camera-renovation
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_hyp_intf.o
