ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/icp_hw/bps_hw
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += bps_dev.o bps_core.o bps_soc.o
