ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_isp/isp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_isp/isp_hw_mgr/hw_utils/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_isp/isp_hw_mgr/hw_utils/irq_controller
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_isp/isp_hw_mgr/isp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += hw_utils/ isp_hw/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_isp_hw_mgr.o cam_ife_hw_mgr.o

