ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_flash_dev.o cam_flash_core.o cam_flash_soc.o
