ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_core/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_utils/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_sync/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_req_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cdm/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_cpas/include/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/camera-renovation/cam_jpeg/jpeg_hw/include/

obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += jpeg_enc_hw/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += jpeg_dma_hw/
obj-$(CONFIG_SPECTRA_CAMERA_RENOVATION) += cam_jpeg_hw_mgr.o
